--[[
  Passport System - one-click installer (auto-generated by tools/package.ps1, do not edit)
  Usage: install server    # run on the server computer
         install client    # run on each client computer
]]
local files = {
  ["lib/config.lua"] = [==[--[[
  Passport System - 共享配置
  服务器与客户端电脑都需要安装本文件(lib/config.lua)。

  外设朝向约定(客户端):
    back   - 有线调制解调器(modem)
    right  - 磁盘驱动器(drive)
    top    - 显示器(monitor, 可选)
    bottom - 打印机(printer, 可选)
  如需修改朝向, 直接改下面的字符串即可。
]]

local config = {
  NAME    = "Passport System",
  VERSION = "1.0.0",

  -- 红石网络协议名(整个系统必须一致)
  PROTOCOL           = "passport",          -- 业务消息协议
  DISCOVERY_PROTOCOL = "passport_discover", -- 服务器发现协议
  DISCOVERY_NAME     = "passport-server",   -- 服务器在发现协议中注册的主机名

  -- 服务器电脑 ID:
  --   0  = 每次启动自动发现(推荐, 依赖 rednet.lookup)
  --   N  = 手动指定服务器电脑 ID(输入 `id` 命令可查看), 可跳过发现过程
  SERVER_ID = 0,

  -- 外设朝向(客户端)
  MODEM_SIDE   = "back",   -- 调制解调器
  DISK_SIDE    = "right",  -- 磁盘驱动器
  MONITOR_SIDE = "top",    -- 显示器(可选)
  PRINTER_SIDE = "bottom", -- 打印机(可选)

  -- 文件路径
  CONFIG_FILE = "/.passport_config",  -- 客户端本地持久化配置
  SERVER_DB   = "/db/passports.dat",  -- 服务器数据库
  DISK_FILE   = "passport.dat",       -- 软盘上的护照文件名

  -- 护照默认有效期(年)
  DEFAULT_VALID_YEARS = 5,
}

-- 读取持久化配置(客户端)
function config.load()
  if fs.exists(config.CONFIG_FILE) then
    local f = fs.open(config.CONFIG_FILE, "r")
    if f then
      local raw = f.readAll()
      f.close()
      local ok, t = pcall(textutils.unserialize, raw)
      if ok and type(t) == "table" and t.SERVER_ID then
        config.SERVER_ID = t.SERVER_ID
      end
    end
  end
end

-- 保存持久化配置(客户端)
function config.save()
  local f = fs.open(config.CONFIG_FILE, "w")
  if f then
    f.write(textutils.serialize({ SERVER_ID = config.SERVER_ID }))
    f.close()
  end
end

return config
]==],
  ["lib/passport.lua"] = [==[--[[
  Passport System - 护照数据模型 & 软盘读写
  服务器与客户端共用本文件。
]]

local config = require("lib.config")
local passport = {}

-- 客户端本地生成一个临时护照编号(服务器登记后可能换成官方编号)
-- 限制在 13 字符以内, 满足软盘标签长度限制
function passport.provisionalID()
  local t = os.time()
  local sub = (os.clock() * 10000) % 10000
  return string.format("PN-%04d-%04d", t % 10000, math.floor(sub))
end

-- 新建护照记录。data: 表单收集的字段表
function passport.new(data)
  data = data or {}
  local validYears = tonumber(data.validYears) or config.DEFAULT_VALID_YEARS
  if validYears < 1 then validYears = 1 end
  local now = os.time()
  local p = {
    id         = (data.id and data.id ~= "") and data.id or passport.provisionalID(),
    name       = data.name or "Unknown",
    age        = tonumber(data.age) or 0,
    gender     = data.gender or "Unknown",
    nation     = data.nation or "Unknown",
    photo      = data.photo or "",
    note       = data.note or "",
    validYears = validYears,
    issued     = os.date("%Y-%m-%d %H:%M:%S", now),
    expiry     = os.date("%Y-%m-%d", now + validYears * 365 * 24 * 3600),
    expires    = now + validYears * 365 * 24 * 3600,
    status     = data.status or "active", -- active / revoked
    stamps     = data.stamps or {},       -- 签证/出入境记录
  }
  return p
end

-- 校验护照有效性。返回 ok, 原因
function passport.validate(p)
  if type(p) ~= "table" or not p.id or p.id == "" then
    return false, "Invalid passport data"
  end
  if p.status == "revoked" then
    return false, "Passport has been revoked"
  end
  if p.expires and os.time() > p.expires then
    return false, "Passport expired (" .. tostring(p.expiry) .. ")"
  end
  return true, "Valid until " .. tostring(p.expiry or "?") .. ")"
end

-- 添加签证/出入境记录。stamp: { type="入境"|"出境"|"签证", country=..., note=... }
-- 返回追加后的记录
function passport.addStamp(p, stamp)
  stamp = stamp or {}
  stamp.time = os.date("%Y-%m-%d %H:%M:%S", os.time())
  stamp.idx = #p.stamps + 1
  table.insert(p.stamps, stamp)
  return stamp
end

-- 护照状态的中文描述
function passport.statusText(p)
  local ok, reason = passport.validate(p)
  return ok and "VALID" or "INVALID"
end

------------------------------------------------------------------------------
-- 软盘读写
------------------------------------------------------------------------------

-- 从软盘读取护照。返回 record, 或 nil, 错误信息
function passport.readDisk(side)
  side = side or config.DISK_SIDE
  if not disk.isPresent(side) then
    return nil, "No disk in drive"
  end
  if not disk.hasData(side) then
    return nil, "Disk has no filesystem (format a blank floppy first)"
  end
  local mount = disk.getMountPath(side) or "disk"
  local path = "/" .. mount .. "/" .. config.DISK_FILE
  if not fs.exists(path) then
    return nil, "No passport file on disk (" .. config.DISK_FILE .. ")"
  end
  local f = fs.open(path, "r")
  if not f then
    return nil, "Cannot open passport file"
  end
  local raw = f.readAll()
  f.close()
  local ok, data = pcall(textutils.unserialize, raw)
  if not ok or type(data) ~= "table" then
    return nil, "Passport file is corrupted or invalid"
  end
  return data
end

-- 写入护照到软盘(先写临时文件再替换, 防止写入中断损坏数据)。
-- 返回 true, 或 nil, 错误信息
function passport.writeDisk(side, p)
  side = side or config.DISK_SIDE
  if not disk.isPresent(side) then
    return nil, "No disk in drive"
  end
  if not disk.hasData(side) then
    return nil, "Disk has no filesystem (format a blank floppy first)"
  end
  local mount = disk.getMountPath(side) or "disk"
  local dir = "/" .. mount
  local path = dir .. "/" .. config.DISK_FILE
  local tmp = dir .. "/." .. config.DISK_FILE .. ".tmp"

  local f = fs.open(tmp, "w")
  if not f then
    return nil, "Cannot write to disk (full or read-only?)"
  end
  f.write(textutils.serialize(p))
  f.close()

  if fs.exists(path) then
    fs.delete(path)
  end
  fs.move(tmp, path)
  disk.setLabel(side, p.id)
  return true
end

return passport
]==],
  ["lib/net.lua"] = [==[--[[
  Passport System - 红石网络通信(客户端用)
  服务发现使用 rednet.host / rednet.lookup (CraftOS 内置机制)。
]]

local config = require("lib.config")
local net = {}

local reqCounter = 0

-- 打开调制解调器(自动找到侧边)
function net.open()
  local modem = peripheral.find("modem")
  if not modem then
    return false, "No modem found (install a wired/wireless modem)"
  end
  local side = peripheral.getName(modem)
  if not rednet.isOpen(side) then
    local ok, err = pcall(rednet.open, side)
    if not ok then
      return false, "Failed to open modem: " .. tostring(err)
    end
  end
  return true
end

-- 自动发现服务器。返回服务器电脑 ID 或 nil
function net.findServer()
  -- 优先用主机名精确查找
  local id = rednet.lookup(config.DISCOVERY_PROTOCOL, config.DISCOVERY_NAME)
  if id then return id end
  -- 退化为任意注册了该协议的电脑
  local ids = { rednet.lookup(config.DISCOVERY_PROTOCOL) }
  if #ids > 0 then return ids[1] end
  return nil
end

-- 获取服务器 ID: 手动配置优先, 否则自动发现
function net.getServerID()
  if config.SERVER_ID and config.SERVER_ID > 0 then
    return config.SERVER_ID
  end
  return net.findServer()
end

-- 生成请求编号(用于匹配响应)
function net.nextReqId()
  reqCounter = reqCounter + 1
  return string.format("%d-%d-%d", os.time(), reqCounter, math.random(1000, 9999))
end

-- 发送业务请求并等待响应。
-- payload: { type="register"|"get"|"stamp"|"update"|"check"|"stats"|"remove", ... }
-- 返回响应表, 超时返回 nil
function net.request(serverId, payload, timeout)
  payload = payload or {}
  payload.reqId = net.nextReqId()
  timeout = timeout or 6

  if not rednet.send(serverId, payload, config.PROTOCOL) then
    return nil
  end
  local deadline = os.time() + timeout
  while os.time() < deadline do
    local sender, msg, proto = rednet.receive(config.PROTOCOL, 0.5)
    if sender == serverId and type(msg) == "table"
      and msg.type == "response" and msg.reqId == payload.reqId then
      return msg
    end
  end
  return nil
end

-- 连接测试
function net.ping(serverId, timeout)
  local resp = net.request(serverId, { type = "ping" }, timeout or 3)
  return resp
end

return net
]==],
  ["lib/tui.lua"] = [==[--[[
  Passport System - TUI 框架
  提供菜单、表单、对话框等界面组件, 支持中文/全角字符(宽字符)对齐。

  所有组件都是阻塞式: 调用后进入自身的事件循环, 返回时界面已处理完毕。
  按 Ctrl+T 可在任意界面退出程序(CraftOS 标准行为)。
]]

local tui = {}

-- 调色板(普通电脑上 term 会自动降级为灰度)
local C = {
  bg      = colors.black,
  border  = colors.gray,
  titleFg = colors.white,
  titleBg = colors.cyan,
  textFg  = colors.white,
  dimFg   = colors.gray,
  accFg   = colors.yellow,
  errBg   = colors.red,
  errFg   = colors.white,
  okBg    = colors.green,
  okFg    = colors.black,
  selBg   = colors.cyan,
  selFg   = colors.black,
}
tui.C = C

------------------------------------------------------------------------------
-- 宽字符工具(中文/全角字符在终端中占 2 格)
------------------------------------------------------------------------------

local function charWidth(cp)
  if cp < 0x1100 then return 1 end
  if cp <= 0x115F then return 2 end
  if cp < 0x2E80 then return 1 end
  if cp <= 0x303E then return 2 end
  if cp == 0x303F then return 1 end
  if cp < 0x3041 then return 1 end
  if cp <= 0x33FF then return 2 end
  if cp < 0x3400 then return 1 end
  if cp <= 0x9FFF then return 2 end
  if cp < 0xA000 then return 1 end
  if cp <= 0xA4CF then return 2 end
  if cp < 0xAC00 then return 1 end
  if cp <= 0xD7A3 then return 2 end
  if cp < 0xF900 then return 1 end
  if cp <= 0xFAFF then return 2 end
  if cp < 0xFE30 then return 1 end
  if cp <= 0xFE4F then return 2 end
  if cp < 0xFF00 then return 1 end
  if cp <= 0xFF60 then return 2 end
  if cp < 0xFFE0 then return 1 end
  if cp <= 0xFFE6 then return 2 end
  if cp >= 0x1F000 then return 2 end
  return 1
end

-- 返回字符串第 i 字节处的下一个 UTF-8 字符的码点与结束位置
-- (对不完整的 UTF-8 序列做防护, 避免 nil 算术错误)
local function utf8Next(s, i)
  if i > #s then return nil end
  local b = s:byte(i)
  local n, cp
  if b < 0x80 then
    n, cp = 1, b
  elseif b < 0xE0 then
    n, cp = 2, (b % 0x20) * 0x40 + (s:byte(i + 1) or 0) % 0x40
  elseif b < 0xF0 then
    n, cp = 3, (b % 0x10) * 0x1000 + ((s:byte(i + 1) or 0) % 0x40) * 0x40 + (s:byte(i + 2) or 0) % 0x40
  else
    n, cp = 4, (b % 0x08) * 0x40000 + ((s:byte(i + 1) or 0) % 0x40) * 0x1000
      + ((s:byte(i + 2) or 0) % 0x40) * 0x40 + (s:byte(i + 3) or 0) % 0x40
  end
  return cp, i + n
end

-- 字符串在终端中的显示宽度
function tui.displayWidth(s)
  local w = 0
  local i = 1
  while i <= #s do
    local cp, nextI = utf8Next(s, i)
    w = w + charWidth(cp)
    i = nextI
  end
  return w
end

-- 按显示宽度填充到 width。align: "left" | "center" | "right"
function tui.pad(s, width, align)
  s = tostring(s or "")
  align = align or "left"
  local w = tui.displayWidth(s)
  if w >= width then return s end
  local fill = width - w
  if align == "center" then
    local l = math.floor(fill / 2)
    return string.rep(" ", l) .. s .. string.rep(" ", fill - l)
  elseif align == "right" then
    return string.rep(" ", fill) .. s
  end
  return s .. string.rep(" ", fill)
end

-- 按显示宽度截断, 不会截断半个中文字符
function tui.truncate(s, width)
  s = tostring(s or "")
  local w = 0
  local i = 1
  while i <= #s do
    local cp, nextI = utf8Next(s, i)
    local cw = charWidth(cp)
    if w + cw > width then
      return s:sub(1, i - 1)
    end
    w = w + cw
    i = nextI
  end
  return s
end

-- 用空格填满一个区域(清屏)
function tui.clearArea(x, y, w, h)
  term.setBackgroundColor(C.bg)
  term.setTextColor(C.bg)
  for row = 1, h do
    term.setCursorPos(x, y + row - 1)
    term.write(string.rep(" ", w))
  end
end

-- 带标题的边框盒
function tui.box(x, y, w, h, title)
  if w < 4 then w = 4 end
  if h < 3 then h = 3 end
  tui.clearArea(x, y, w, h)
  term.setBackgroundColor(C.bg)
  term.setTextColor(C.border)
  term.setCursorPos(x, y)
  term.write("┌" .. string.rep("─", w - 2) .. "┐")
  for r = 2, h - 1 do
    term.setCursorPos(x, y + r - 1)
    term.write("│")
    term.setCursorPos(x + w - 1, y + r - 1)
    term.write("│")
  end
  term.setCursorPos(x, y + h - 1)
  term.write("└" .. string.rep("─", w - 2) .. "┘")
  if title and title ~= "" then
    term.setBackgroundColor(C.titleBg)
    term.setTextColor(C.titleFg)
    term.setCursorPos(x + 2, y)
    term.write(tui.truncate(title, w - 4))
    term.setBackgroundColor(C.bg)
    term.setTextColor(C.border)
  end
end

-- 全屏主界面框架: 顶部标题 + 底部状态栏, 返回内容区高度
function tui.frame(title, statusText)
  local w, h = term.getSize()
  term.setBackgroundColor(C.bg)
  term.clear()
  -- 标题栏
  term.setBackgroundColor(C.titleBg)
  term.setTextColor(C.titleFg)
  term.setCursorPos(1, 1)
  term.write(tui.pad(" " .. tui.truncate(title, w - 2), w))
  -- 状态栏
  tui.statusBar(statusText)
  term.setBackgroundColor(C.bg)
  return h
end

-- 底部状态栏
function tui.statusBar(text)
  local w, h = term.getSize()
  term.setBackgroundColor(colors.gray)
  term.setTextColor(colors.black)
  term.setCursorPos(1, h)
  term.write(tui.pad(" " .. tui.truncate(tostring(text or ""), w - 2), w))
  term.setBackgroundColor(C.bg)
end

------------------------------------------------------------------------------
-- 菜单
------------------------------------------------------------------------------

-- 垂直菜单。options: { {label=..., desc=...}, ... }
-- 返回选中项的索引(1..n), 按 Esc 返回 nil
function tui.menu(title, options, width)
  local w, h = term.getSize()
  local mw = width or 46
  local mh = #options + 4
  if mw > w - 2 then mw = w - 2 end
  if mh > h - 2 then mh = h - 2 end
  local mx = math.max(1, math.floor((w - mw) / 2))
  local my = math.max(1, math.floor((h - mh) / 2))

  local sel = 1

  local function draw()
    tui.box(mx, my, mw, mh, title)
    for i, opt in ipairs(options) do
      local y = my + 2 + (i - 1)
      if i == sel then
        term.setBackgroundColor(C.selBg)
        term.setTextColor(C.selFg)
      else
        term.setBackgroundColor(C.bg)
        term.setTextColor(C.textFg)
      end
      term.setCursorPos(mx + 1, y)
      term.write(tui.pad("  " .. tostring(i) .. ") " .. opt.label, mw - 3))
    end
    -- 底部提示
    term.setBackgroundColor(C.bg)
    term.setTextColor(C.dimFg)
    term.setCursorPos(mx + 1, my + mh - 1)
    term.write(tui.pad("^v select  Enter confirm  Esc back", mw - 2))
  end

  draw()
  while true do
    local ev, p1 = os.pullEvent()
    if ev == "key" then
      if p1 == keys.up then
        sel = sel - 1
        if sel < 1 then sel = #options end
        draw()
      elseif p1 == keys.down then
        sel = sel + 1
        if sel > #options then sel = 1 end
        draw()
      elseif p1 == keys.enter then
        return sel
      elseif p1 == keys.esc then
        return nil
      end
    elseif ev == "char" then
      local n = tonumber(p1)
      if n and n >= 1 and n <= #options then
        return n
      end
    end
  end
end

------------------------------------------------------------------------------
-- 表单
------------------------------------------------------------------------------

-- 表单。fields: { {key=..., label=..., type="text"|"number"|"password"|"choice",
--                  choices={...}, default=...}, ... }
-- 自动附加一个"确认提交"行。返回 { key=value }, 按 Esc 返回 nil
function tui.form(title, fields)
  local w, h = term.getSize()
  local fw = 48
  local fh = #fields + 5
  if fw > w - 2 then fw = w - 2 end
  if fh > h - 2 then fh = h - 2 end
  local fx = math.max(1, math.floor((w - fw) / 2))
  local fy = math.max(1, math.floor((h - fh) / 2))

  local values = {}
  for _, f in ipairs(fields) do
    values[f.key] = f.default or ""
  end

  local cur = 1
  local hint = ""

  local function fieldValue(f)
    local v = values[f.key]
    if f.type == "password" and v ~= "" then
      return string.rep("*", tui.displayWidth(v))
    elseif f.type == "choice" then
      local n = tonumber(v) or 1
      return (f.choices and f.choices[n]) or tostring(v)
    end
    return tostring(v)
  end

  local function draw()
    tui.box(fx, fy, fw, fh, title)
    -- 字段行
    for i, f in ipairs(fields) do
      local y = fy + 2 + (i - 1)
      if i == cur then
        term.setBackgroundColor(C.selBg)
        term.setTextColor(C.selFg)
      else
        term.setBackgroundColor(C.bg)
        term.setTextColor(C.textFg)
      end
      term.setCursorPos(fx + 1, y)
      term.write(tui.pad(f.label .. ":", 12))
      local v = fieldValue(f)
      if i ~= cur then
        term.write(tui.pad(tui.truncate(v, fw - 15), fw - 15))
      else
        term.write(tui.pad("", fw - 15))
      end
    end
    -- 提交行
    local sy = fy + 2 + #fields
    if #fields + 1 == cur then
      term.setBackgroundColor(C.selBg)
      term.setTextColor(C.selFg)
    else
      term.setBackgroundColor(C.bg)
      term.setTextColor(C.textFg)
    end
    term.setCursorPos(fx + 1, sy)
    term.write(tui.pad("  [OK] Submit", fw - 2))
    -- 提示行
    term.setBackgroundColor(C.bg)
    term.setTextColor(C.dimFg)
    term.setCursorPos(fx + 1, fy + fh - 1)
    term.write(tui.pad(hint ~= "" and hint or "^v switch  Enter edit/submit  Esc cancel", fw - 2))
  end

  local function isChoice(i)
    return fields[i].type == "choice"
  end

  local function cycleChoice(i, dir)
    local f = fields[i]
    local n = tonumber(values[f.key]) or 1
    local total = #(f.choices or {})
    if total < 1 then return end
    n = n + dir
    if n < 1 then n = total elseif n > total then n = 1 end
    values[f.key] = tostring(n)
  end

  local function editField(i)
    local f = fields[i]
    local y = fy + 2 + (i - 1)
    if f.type == "choice" then
      cycleChoice(i, 1)
      return
    end
    term.setCursorPos(fx + 14, y)
    term.setBackgroundColor(C.bg)
    term.setTextColor(C.textFg)
    term.setCursorBlink(true)
    local v
    if f.type == "password" then
      v = read("*", nil, nil, values[f.key])
    else
      v = read(nil, nil, nil, values[f.key])
    end
    term.setCursorBlink(false)
    if v then
      if f.type == "number" and v ~= "" and not tonumber(v) then
        hint = "Error: enter a number"
        draw()
        return
      end
      values[f.key] = v
    end
    hint = ""
  end

  draw()
  while true do
    local ev, p1 = os.pullEvent()
    if ev == "key" then
      if p1 == keys.up then
        cur = cur - 1
        if cur < 1 then cur = #fields + 1 end
        hint = ""
        draw()
      elseif p1 == keys.down then
        cur = cur + 1
        if cur > #fields + 1 then cur = 1 end
        hint = ""
        draw()
      elseif p1 == keys.enter then
        if cur <= #fields then
          editField(cur)
        else
          -- 校验必填
          local missing = {}
          for _, f in ipairs(fields) do
            if f.required and (values[f.key] == nil or values[f.key] == "") then
              table.insert(missing, f.label)
            end
          end
          if #missing > 0 then
            hint = "Required: " .. table.concat(missing, ", ")
            draw()
          else
            return values
          end
        end
      elseif p1 == keys.left and isChoice(cur) then
        cycleChoice(cur, -1)
        draw()
      elseif p1 == keys.right and isChoice(cur) then
        cycleChoice(cur, 1)
        draw()
      elseif p1 == keys.esc then
        return nil
      end
    elseif ev == "char" and isChoice(cur) then
      local c = tonumber(p1)
      if c then
        values[fields[cur].key] = tostring(c)
        draw()
      end
    end
  end
end

------------------------------------------------------------------------------
-- 对话框
------------------------------------------------------------------------------

-- 消息框: 显示若干行文本, 按任意键关闭
-- lines: string 或 string 数组
function tui.msgBox(title, lines, okLabel)
  if type(lines) == "string" then lines = { lines } end
  okLabel = okLabel or "Press any key to close"
  local w, h = term.getSize()
  local mw = 48
  local mh = #lines + 4
  if mw > w - 2 then mw = w - 2 end
  if mh > h - 2 then mh = h - 2 end
  local mx = math.max(1, math.floor((w - mw) / 2))
  local my = math.max(1, math.floor((h - mh) / 2))

  tui.box(mx, my, mw, mh, title)
  term.setBackgroundColor(C.bg)
  term.setTextColor(C.textFg)
  for i, line in ipairs(lines) do
    term.setCursorPos(mx + 1, my + 2 + (i - 1))
    term.write(tui.pad(tui.truncate(line, mw - 2), mw - 2))
  end
  term.setTextColor(C.dimFg)
  term.setCursorPos(mx + 1, my + mh - 1)
  term.write(tui.pad(okLabel, mw - 2, "center"))

  os.pullEvent("key")
  os.pullEvent("key_up")
  return true
end

-- 确认框: 返回 boolean
function tui.confirm(title, lines, yesLabel, noLabel)
  if type(lines) == "string" then lines = { lines } end
  yesLabel = yesLabel or "Y Yes"
  noLabel = noLabel or "N No"
  local w, h = term.getSize()
  local mw = 48
  local mh = #lines + 4
  if mw > w - 2 then mw = w - 2 end
  if mh > h - 2 then mh = h - 2 end
  local mx = math.max(1, math.floor((w - mw) / 2))
  local my = math.max(1, math.floor((h - mh) / 2))

  tui.box(mx, my, mw, mh, title)
  term.setBackgroundColor(C.bg)
  term.setTextColor(C.textFg)
  for i, line in ipairs(lines) do
    term.setCursorPos(mx + 1, my + 2 + (i - 1))
    term.write(tui.pad(tui.truncate(line, mw - 2), mw - 2))
  end
  term.setTextColor(C.dimFg)
  term.setCursorPos(mx + 1, my + mh - 1)
  term.write(tui.pad(("  %s    %s"):format(yesLabel, noLabel), mw - 2, "center"))

  while true do
    local ev, p1 = os.pullEvent()
    if ev == "key" then
      if p1 == keys.y then return true end
      if p1 == keys.n then return false end
      if p1 == keys.enter then return true end
      if p1 == keys.esc then return false end
    elseif ev == "char" then
      local c = p1:lower()
      if c == "y" then return true end
      if c == "n" then return false end
    end
  end
end

return tui
]==],
  ["lib/db.lua"] = [==[--[[
  Passport System - 服务器数据库
  数据保存在 /db/passports.dat (textutils.serialize 序列化),
  采用"写临时文件再替换"的原子写入, 崩溃不丢数据。
]]

local config = require("lib.config")
local db = {}

-- 载入数据库(不存在则返回空库)
function db.load()
  local data = { seq = 1, passports = {} }
  if fs.exists(config.SERVER_DB) then
    local f = fs.open(config.SERVER_DB, "r")
    if f then
      local raw = f.readAll()
      f.close()
      local ok, t = pcall(textutils.unserialize, raw)
      if ok and type(t) == "table" and type(t.passports) == "table" then
        data = t
      end
    end
  end
  return data
end

-- 保存数据库(原子写入)
function db.save(data)
  local ok, err = pcall(fs.makeDir, "/db")
  if not ok then return false, err end
  local tmp = config.SERVER_DB .. ".tmp"
  local f = fs.open(tmp, "w")
  if not f then return false, "Cannot write database" end
  f.write(textutils.serialize(data))
  f.close()
  if fs.exists(config.SERVER_DB) then
    fs.delete(config.SERVER_DB)
  end
  fs.move(tmp, config.SERVER_DB)
  return true
end

-- 注册(新签)或更新护照。返回 record, isNew
-- 若 rec.id 为空则分配官方编号 PN-YYYY-NNNN
function db.register(data, rec)
  local id = rec.id or ""
  if id == "" then
    id = string.format("PN-%s-%04d", os.date("%Y", os.time()), data.seq)
    data.seq = data.seq + 1
    rec.id = id
    return rec, true
  end
  local isNew = data.passports[id] == nil
  rec.id = id
  data.passports[id] = rec
  return rec, isNew
end

-- 按 ID 查询
function db.get(data, id)
  return data.passports[id]
end

-- 删除
function db.remove(data, id)
  if data.passports[id] then
    data.passports[id] = nil
    return true
  end
  return false
end

-- 追加盖章记录(自动保存由调用方负责)
function db.addStamp(data, id, stamp)
  local rec = data.passports[id]
  if not rec then
    return nil, "Passport not found: " .. tostring(id)
  end
  local pmod = require("lib.passport")
  pmod.addStamp(rec, stamp)
  return rec
end

-- 吊销
function db.revoke(data, id)
  local rec = data.passports[id]
  if not rec then
    return nil, "Passport not found: " .. tostring(id)
  end
  rec.status = "revoked"
  return rec
end

-- 统计
function db.stats(data)
  local total, active, revoked, expired = 0, 0, 0, 0
  local now = os.time()
  for _, p in pairs(data.passports) do
    total = total + 1
    if p.status == "revoked" then
      revoked = revoked + 1
    elseif p.expires and now > p.expires then
      expired = expired + 1
    else
      active = active + 1
    end
  end
  return {
    total = total,
    active = active,
    revoked = revoked,
    expired = expired,
    nextID = string.format("PN-%s-%04d", os.date("%Y", os.time()), data.seq),
  }
end

return db
]==],
  ["server.lua"] = [==[--[[
  Passport System - 中央服务器
  ============================
  负责保存所有护照数据(/db/passports.dat), 通过 rednet 向客户端提供服务。
  部署到游戏中的"服务器电脑"后, 可重命名为 startup.lua 实现开机自启。

  在游戏内输入 `id` 命令可查看本机电脑 ID, 供客户端手动指定使用。
]]

local config = require("lib.config")
local db = require("lib.db")
local passport = require("lib.passport")

local data = db.load()

local function log(msg)
  print(("[%s] %s"):format(os.date("%H:%M:%S"), tostring(msg)))
end

-- 向客户端回包
local function reply(client, reqId, ok, payload)
  local resp = { type = "response", reqId = reqId, ok = ok, data = payload }
  rednet.send(client, resp, config.PROTOCOL)
end

-- 处理业务请求
local function handle(client, msg)
  local t = msg.type
  if t == "ping" then
    reply(client, msg.reqId, true, {
      pong = true,
      version = config.VERSION,
      time = os.time(),
      serverID = os.getComputerID(),
    })
  elseif t == "register" then
    if type(msg.data) ~= "table" then
      reply(client, msg.reqId, false, { error = "Bad data format" })
      return
    end
    local rec, isNew = db.register(data, msg.data)
    local ok, err = db.save(data)
    if not ok then
      reply(client, msg.reqId, false, { error = "Server DB write failed: " .. tostring(err) })
      return
    end
    log(("Registered %s (%s) name=%s"):format(rec.id, isNew and "new" or "update", rec.name))
    reply(client, msg.reqId, true, { record = rec, isNew = isNew })
  elseif t == "get" then
    local rec = db.get(data, msg.id)
    if rec then
      reply(client, msg.reqId, true, { record = rec })
    else
      reply(client, msg.reqId, false, { error = "Passport not found: " .. tostring(msg.id) })
    end
  elseif t == "stamp" then
    if type(msg.stamp) ~= "table" then
      reply(client, msg.reqId, false, { error = "Bad stamp data" })
      return
    end
    local rec, err = db.addStamp(data, msg.id, msg.stamp)
    if rec then
      db.save(data)
      log(("Stamped %s: %s / %s"):format(msg.id, msg.stamp.type or "?", msg.stamp.country or "?"))
      reply(client, msg.reqId, true, { record = rec })
    else
      reply(client, msg.reqId, false, { error = err or "Stamp failed" })
    end
  elseif t == "update" then
    local rec = msg.data
    if type(rec) ~= "table" or not rec.id then
      reply(client, msg.reqId, false, { error = "Bad data format" })
      return
    end
    if not db.get(data, rec.id) then
      reply(client, msg.reqId, false, { error = "Passport not found, register it first" })
      return
    end
    data.passports[rec.id] = rec
    db.save(data)
    log(("Updated passport %s"):format(rec.id))
    reply(client, msg.reqId, true, { record = rec })
  elseif t == "check" then
    local rec = db.get(data, msg.id)
    if not rec then
      reply(client, msg.reqId, false, { error = "Passport not found: " .. tostring(msg.id) })
      return
    end
    local ok, reason = passport.validate(rec)
    reply(client, msg.reqId, ok, { record = rec, reason = reason })
  elseif t == "revoke" then
    local rec, err = db.revoke(data, msg.id)
    if rec then
      db.save(data)
      log(("Revoked passport %s"):format(msg.id))
      reply(client, msg.reqId, true, { record = rec })
    else
      reply(client, msg.reqId, false, { error = err or "Revoke failed" })
    end
  elseif t == "remove" then
    local ok = db.remove(data, msg.id)
    if ok then db.save(data) end
    log(("Deleted passport %s: %s"):format(msg.id, ok and "ok" or "not found"))
    reply(client, msg.reqId, ok, {})
  elseif t == "stats" then
    reply(client, msg.reqId, true, { stats = db.stats(data) })
  else
    reply(client, msg.reqId, false, { error = "Unknown request type: " .. tostring(t) })
  end
end

-- 开机画面
local function banner()
  term.clear()
  term.setCursorPos(1, 1)
  term.setTextColor(colors.cyan)
  print("============================================")
  print("    Passport System · Central Server v" .. config.VERSION)
  print("============================================")
  term.setTextColor(colors.white)
  print()
  print("  Computer ID: " .. os.getComputerID())
  print("  Database file: " .. config.SERVER_DB)
  local st = db.stats(data)
  print("  Passports: " .. st.total .. " (valid " .. st.active
    .. " / revoked " .. st.revoked .. " / expired " .. st.expired .. ")")
  print("  Next ID: " .. st.nextID)
  print()
  print("  Running... Ctrl+T stop, Ctrl+R restart")
  print("--------------------------------------------------")
end

-- 启动前检查
local modem = peripheral.find("modem")
if not modem then
  term.setTextColor(colors.red)
  print("Error: no modem attached!")
  print("Place a wired modem on the computer (back or any side).")
  term.setTextColor(colors.white)
  return
end
local ok, err = pcall(rednet.open, peripheral.getName(modem))
if not ok then
  term.setTextColor(colors.red)
  print("Error: failed to open modem: " .. tostring(err))
  term.setTextColor(colors.white)
  return
end

-- 注册发现服务(供客户端 rednet.lookup)
local hostOk, hostErr = pcall(rednet.host, config.DISCOVERY_PROTOCOL, config.DISCOVERY_NAME)
if not hostOk then
  term.setTextColor(colors.yellow)
  print("Warning: failed to register discovery service: " .. tostring(hostErr))
  print("       (another server may already be running?)")
  term.setTextColor(colors.white)
end

banner()

parallel.waitForAny(
  -- 业务请求循环
  function()
    while true do
      local client, msg, proto = rednet.receive(config.PROTOCOL)
      if type(msg) == "table" then
        local okc, errc = pcall(handle, client, msg)
        if not okc then
          log(("Error handling request: %s"):format(errc))
          reply(client, msg.reqId, false, { error = "Server internal error" })
        end
      end
    end
  end,
  -- 每秒刷新一次状态行
  function()
    while true do
      os.sleep(1)
      local w, h = term.getSize()
      local st = db.stats(data)
      term.setBackgroundColor(colors.gray)
      term.setTextColor(colors.black)
      term.setCursorPos(1, h)
      local line = ("  Passports %d  valid %d  revoked %d  expired %d"):format(
        st.total, st.active, st.revoked, st.expired)
      term.write(line .. string.rep(" ", w - #line))
      term.setBackgroundColor(colors.black)
    end
  end
)
]==],
  ["client.lua"] = [==[--[[
  Passport System - 客户端
  ========================
  部署到游戏中的"客户端电脑"(如边境检查站/出入境大厅)。
  可重命名为 startup.lua 实现开机自启。

  功能:
    1. 签发新护照(写入软盘 + 上传服务器)
    2. 查看护照(终端/显示器展示, 可打印)
    3. 编辑护照
    4. 签证盖章(入境/出境/签证, 打印回执)
    5. 双向同步: 服务器 ↔ 软盘
    6. 服务器状态 / 设置
]]

local config = require("lib.config")
local tui = require("lib.tui")
local passport = require("lib.passport")
local net = require("lib.net")

config.load()

------------------------------------------------------------------------------
-- 状态
------------------------------------------------------------------------------

local periph = { disk = false, monitor = false, printer = false }
local serverId = nil

local function scanPeriphs()
  periph.disk    = peripheral.isPresent(config.DISK_SIDE)
  periph.monitor = peripheral.isPresent(config.MONITOR_SIDE)
  periph.printer = peripheral.isPresent(config.PRINTER_SIDE)
end

local function refreshServer()
  if not rednet.isOpen() then
    serverId = nil -- 调制解调器未打开, 跳过查找
    return
  end
  serverId = net.getServerID()
end

local function statusText()
  return string.format("Disk:%s Mon:%s Print:%s | %s",
    periph.disk and "Y" or "N",
    periph.monitor and "Y" or "N",
    periph.printer and "Y" or "N",
    serverId and ("Server #" .. serverId) or "Server offline")
end

-- 把表单里的 choice 值(索引字符串)转成实际选项
local function choiceValue(choices, v)
  local n = tonumber(v) or 1
  local c = choices[n]
  return c or tostring(v)
end

------------------------------------------------------------------------------
-- 显示器展示
------------------------------------------------------------------------------

local function monitorShow(p)
  if not periph.monitor then return false end
  local mon = peripheral.wrap(config.MONITOR_SIDE)
  if not mon then return false end
  local mw, mh = mon.getSize()
  if mw >= 60 then
    mon.setTextScale(0.5)
  elseif mw >= 40 then
    mon.setTextScale(1)
  end
  local w, h = mon.getSize()
  mon.clear()

  local ok, reason = passport.validate(p)
  local bg = ok and colors.green or colors.red

  -- 顶部横幅(全宽背景色)
  mon.setBackgroundColor(bg)
  mon.setTextColor(colors.white)
  mon.setCursorPos(1, 1)
  mon.write(tui.pad("* P A S S P O R T *", w, "center"))

  -- 正文
  mon.setBackgroundColor(colors.black)
  mon.setTextColor(colors.white)
  local lines = {
    "ID     : " .. p.id,
    "Name   : " .. p.name,
    "Age    : " .. tostring(p.age or 0),
    "Gender : " .. p.gender,
    "Nationality : " .. p.nation,
    "Photo  : " .. (p.photo and p.photo ~= "" and p.photo or "None"),
    "Issued : " .. p.issued,
    "Expiry : " .. p.expiry,
    "Status : " .. (ok and "VALID" or "INVALID"),
    "Stamps : " .. #(p.stamps or {}),
  }
  local y = 3
  for _, line in ipairs(lines) do
    if y < h then
      mon.setCursorPos(1, y)
      mon.write(tui.truncate(line, w))
      y = y + 1
    end
  end
  -- 底部状态条
  mon.setBackgroundColor(bg)
  mon.setTextColor(colors.white)
  mon.setCursorPos(1, h)
  mon.write(tui.pad(tui.truncate(reason or "", w), w, "center"))
  mon.setBackgroundColor(colors.black)
  return true
end

------------------------------------------------------------------------------
-- 打印机
------------------------------------------------------------------------------

-- 打印一页文字。lines 为字符串数组, 每行一次 write(不依赖光标自动推进)。
local function printerPage(title, lines)
  if not periph.printer then return false, "No printer" end
  local pr = peripheral.wrap(config.PRINTER_SIDE)
  if not pr then return false, "Printer unavailable" end
  if pr.getInkLevel() < 1 or pr.getPaperLevel() < 1 then
    return false, "Printer out of ink or paper"
  end
  if not pr.newPage() then
    return false, "Cannot start new page"
  end
  local pw, ph = pr.getPageSize()
  pr.setPageTitle(title)
  local y = 1
  for _, line in ipairs(lines) do
    if y > ph then break end
    pr.setCursorPos(1, y)
    pr.write(tui.truncate(tostring(line), pw))
    y = y + 1
  end
  if not pr.endPage() then
    return false, "Failed to end page"
  end
  return true
end

local function passportPageLines(p)
  local ok, reason = passport.validate(p)
  return {
    "==================================",
    "         P A S S P O R T",
    "==================================",
    "ID       : " .. p.id,
    "NAME     : " .. p.name,
    "AGE      : " .. tostring(p.age or 0),
    "GENDER   : " .. p.gender,
    "NATIONAL : " .. p.nation,
    "PHOTO    : " .. (p.photo and p.photo ~= "" and p.photo or "-"),
    "----------------------------------",
    "ISSUED   : " .. p.issued,
    "EXPIRES  : " .. p.expiry,
    "STATUS   : " .. (ok and "VALID" or "INVALID"),
    "STAMPS   : " .. #(p.stamps or {}),
    "==================================",
  }
end

local function visaReceiptLines(p, stamp)
  local stype = { ["Entry"] = "IN", ["Exit"] = "OUT", ["Visa"] = "VISA" }
  return {
    "==============================",
    "      VISA STAMP RECEIPT",
    "==============================",
    "ID      : " .. p.id,
    "NAME    : " .. p.name,
    "TYPE    : " .. (stype[stamp.type] or stamp.type),
    "COUNTRY : " .. stamp.country,
    "TIME    : " .. stamp.time,
    "==============================",
    "   +---------------------+",
    "   |     STAMP SEAL      |",
    "   +---------------------+",
    "==============================",
  }
end

------------------------------------------------------------------------------
-- 护照详情全屏视图
------------------------------------------------------------------------------

local function showPassport(p)
  local w, h = term.getSize()
  local ok, reason = passport.validate(p)
  local stamps = p.stamps or {}
  local perPage = math.max(3, h - 14)
  local pages = math.max(1, math.ceil(#stamps / perPage))
  local page = 1

  local function draw()
    term.setBackgroundColor(colors.black)
    term.clear()
    -- 标题栏
  term.setBackgroundColor(colors.cyan)
  term.setTextColor(colors.white)
  term.setCursorPos(1, 1)
  term.write(tui.pad(" " .. tui.truncate("Passport Details  " .. p.id, w - 2), w))

    local y = 2
    local function line(text, color)
      y = y + 1
      if y > h - 2 then return end
      term.setBackgroundColor(colors.black)
      term.setTextColor(color or colors.white)
      term.setCursorPos(1, y)
      term.write(tui.truncate(text, w))
    end

    line("")
    line(("Name: %s    Age: %d    Gender: %s"):format(p.name, p.age or 0, p.gender))
    line(("Nationality: %s    Photo: %s"):format(p.nation, (p.photo and p.photo ~= "") and p.photo or "None"))
    line(("Issued: %s    Expires: %s"):format(p.issued, p.expiry))
    if p.note and p.note ~= "" then
      line("Note: " .. p.note)
    end
    line("Status: " .. (ok and "VALID" or "INVALID") .. "  ·  " .. (reason or ""))

    y = y + 2
    term.setBackgroundColor(colors.black)
    term.setTextColor(colors.gray)
    term.setCursorPos(1, y)
    term.write(tui.truncate(("-- Visa Records (%d)  Page %d/%d --"):format(#stamps, page, pages), w))

    y = y + 1
    local startIdx = (page - 1) * perPage + 1
    for i = startIdx, math.min(startIdx + perPage - 1, #stamps) do
      local s = stamps[i]
      term.setBackgroundColor(colors.black)
      term.setTextColor(colors.white)
      term.setCursorPos(1, y)
      term.write(tui.truncate(("[%d] %s | %s | %s"):format(i, s.type or "?", s.country or "?", s.time or ""), w))
      y = y + 1
      if y > h - 2 then break end
    end

    term.setBackgroundColor(colors.black)
    term.setTextColor(colors.gray)
    term.setCursorPos(1, h - 1)
    term.write(tui.truncate("< > page  P print  M monitor  Esc back", w))
  end

  draw()
  while true do
    local ev, p1 = os.pullEvent()
    if ev == "key" then
      if p1 == keys.left then
        page = page - 1
        if page < 1 then page = pages end
        draw()
      elseif p1 == keys.right then
        page = page + 1
        if page > pages then page = 1 end
        draw()
      elseif p1 == keys.esc then
        return
      end
    elseif ev == "char" then
      local c = p1:lower()
      if c == "p" then
        local okp, errp = printerPage("Passport " .. p.id, passportPageLines(p))
        if okp then
          tui.msgBox("Print", { "Passport page printed!" })
        else
          tui.msgBox("Print Failed", { errp or "Unknown error" })
        end
        draw()
      elseif c == "m" then
        local shown = monitorShow(p)
        if not shown then
          tui.msgBox("Monitor", { "No monitor (" .. config.MONITOR_SIDE .. ")" })
          draw()
        end
      end
    end
  end
end

------------------------------------------------------------------------------
-- 各功能
------------------------------------------------------------------------------

local GENDER_CHOICES = { "Male", "Female", "Other" }
local STAMP_TYPES = { "Entry", "Exit", "Visa" }

local function actIssue()
  if not periph.disk then
    tui.msgBox("Issue Passport", { "No disk drive (" .. config.DISK_SIDE .. ")", "Place a disk drive with a floppy inserted" })
    return
  end
  local values = tui.form("Issue New Passport", {
    { key = "name",       label = "Name",       type = "text",   required = true, default = "" },
    { key = "age",        label = "Age",        type = "number" },
    { key = "gender",     label = "Gender",     type = "choice", choices = GENDER_CHOICES, default = "1" },
    { key = "nation",     label = "Nationality", type = "text",  default = "China" },
    { key = "photo",      label = "Photo Desc", type = "text" },
    { key = "note",       label = "Note",       type = "text" },
    { key = "validYears", label = "Valid Years", type = "number", default = tostring(config.DEFAULT_VALID_YEARS) },
  })
  if not values then return end

  local p = passport.new({
    name = values.name,
    age = tonumber(values.age),
    gender = choiceValue(GENDER_CHOICES, values.gender),
    nation = values.nation,
    photo = values.photo,
    note = values.note,
    validYears = tonumber(values.validYears),
  })

  local okw, errw = passport.writeDisk(config.DISK_SIDE, p)
  if not okw then
    tui.msgBox("Issue Failed", { errw or "Disk write failed" })
    return
  end

  if serverId then
    local resp = net.request(serverId, { type = "register", data = p }, 6)
    if resp and resp.ok then
      local saved = resp.data.record
      if saved and saved.id ~= p.id then
        p = saved -- 服务器分配了官方编号, 回写软盘
        passport.writeDisk(config.DISK_SIDE, p)
      end
      tui.msgBox("Issue Successful", {
        "Passport written to disk and registered on server",
        "ID      : " .. p.id,
        "Name    : " .. p.name,
        "Expires : " .. p.expiry,
      })
      if periph.printer and tui.confirm("Print Passport Page?", { "Print a souvenir passport page?" }) then
        local okp, errp = printerPage("Passport " .. p.id, passportPageLines(p))
        if not okp then tui.msgBox("Print Failed", { errp or "Unknown error" }) end
      end
    else
      local e = (resp and resp.data and resp.data.error) or "Server not responding"
      tui.msgBox("Warning", {
        "Not registered (server offline?)",
        "Reason: " .. tostring(e),
        "Passport saved to disk; you can \"Upload: Disk to Server\" later",
      })
    end
  else
    tui.msgBox("Issued (Local Only)", {
      "Server offline; passport saved to disk only",
      "ID: " .. p.id,
      "Choose \"Upload: Disk to Server\" from the menu later",
    })
  end
  monitorShow(p)
end

local function actView()
  if not periph.disk then
    tui.msgBox("View Passport", { "No disk drive (" .. config.DISK_SIDE .. ")" })
    return
  end
  local p, err = passport.readDisk(config.DISK_SIDE)
  if not p then
    tui.msgBox("View Passport", { err or "Read failed" })
    return
  end
  showPassport(p)
end

local function actEdit()
  if not periph.disk then
    tui.msgBox("Edit Passport", { "No disk drive (" .. config.DISK_SIDE .. ")" })
    return
  end
  local p, err = passport.readDisk(config.DISK_SIDE)
  if not p then
    tui.msgBox("Edit Passport", { err or "Read failed" })
    return
  end
  local curGender = 1
  for i, g in ipairs(GENDER_CHOICES) do
    if g == p.gender then curGender = i end
  end
  local values = tui.form("Edit Passport " .. p.id, {
    { key = "name",   label = "Name",        type = "text",   required = true, default = p.name },
    { key = "age",    label = "Age",         type = "number", default = tostring(p.age or "") },
    { key = "gender", label = "Gender",      type = "choice", choices = GENDER_CHOICES, default = tostring(curGender) },
    { key = "nation", label = "Nationality", type = "text",   default = p.nation },
    { key = "photo",  label = "Photo Desc",  type = "text",   default = p.photo },
    { key = "note",   label = "Note",        type = "text",   default = p.note },
  })
  if not values then return end

  p.name = values.name
  p.age = tonumber(values.age) or p.age
  p.gender = choiceValue(GENDER_CHOICES, values.gender)
  p.nation = values.nation
  p.photo = values.photo
  p.note = values.note

  local okw, errw = passport.writeDisk(config.DISK_SIDE, p)
  if not okw then
    tui.msgBox("Edit Failed", { errw or "Disk write failed" })
    return
  end
  if serverId then
    local resp = net.request(serverId, { type = "update", data = p }, 6)
    if resp and resp.ok then
      tui.msgBox("Edit Complete", { "Saved to disk and synced to server" })
    else
      local e = (resp and resp.data and resp.data.error) or "Server not responding"
      tui.msgBox("Saved to Disk", { "Server sync failed: " .. tostring(e), "Use \"Upload: Disk to Server\" to retry later" })
    end
  else
    tui.msgBox("Saved to Disk", { "Server offline, not synced" })
  end
  monitorShow(p)
end

local function actStamp()
  if not periph.disk then
    tui.msgBox("Stamp Visa", { "No disk drive (" .. config.DISK_SIDE .. ")" })
    return
  end
  local p, err = passport.readDisk(config.DISK_SIDE)
  if not p then
    tui.msgBox("Stamp Visa", { err or "Read failed" })
    return
  end
  local ok, reason = passport.validate(p)
  if not ok then
    tui.msgBox("Cannot Stamp", { "This passport cannot be stamped: " .. reason })
    return
  end
  local values = tui.form("Stamp Visa · " .. p.id, {
    { key = "type",    label = "Stamp Type",   type = "choice", choices = STAMP_TYPES, default = "1" },
    { key = "country", label = "Country/Port", type = "text",   required = true },
    { key = "note",    label = "Note",         type = "text" },
  })
  if not values then return end

  local stamp = {
    type = choiceValue(STAMP_TYPES, values.type),
    country = values.country,
    note = values.note,
  }
  passport.addStamp(p, stamp)

  local okw, errw = passport.writeDisk(config.DISK_SIDE, p)
  if not okw then
    tui.msgBox("Stamp Failed", { errw or "Disk write failed" })
    return
  end

  local synced = false
  if serverId then
    local resp = net.request(serverId, { type = "stamp", id = p.id, stamp = stamp }, 6)
    if resp and resp.ok then
      synced = true
    else
      local e = (resp and resp.data and resp.data.error) or "Server not responding"
      tui.msgBox("Stamp Complete (Not Synced)", {
        "Server sync failed: " .. tostring(e),
        "Stamp saved to disk",
      })
    end
  end
  if synced then
    tui.msgBox("Stamp Complete", {
      ("Stamped: %s / %s"):format(stamp.type, stamp.country),
      "Time: " .. stamp.time,
      "Synced to server",
    })
  end
  if periph.printer and tui.confirm("Print Receipt?", { "Print the visa stamp receipt?" }) then
    local okp, errp = printerPage("Visa " .. stamp.type .. " " .. p.id, visaReceiptLines(p, stamp))
    if not okp then tui.msgBox("Print Failed", { errp or "Unknown error" }) end
  end
  monitorShow(p)
end

local function actSyncDown()
  if not periph.disk then
    tui.msgBox("Sync", { "No disk drive (" .. config.DISK_SIDE .. ")" })
    return
  end
  if not serverId then refreshServer() end
  if not serverId then
    tui.msgBox("Sync Failed", { "No server found, cannot sync" })
    return
  end
  local id = disk.isPresent(config.DISK_SIDE) and disk.getLabel(config.DISK_SIDE) or nil
  if not id then
    -- 从软盘上的护照文件读取编号
    local p, err = passport.readDisk(config.DISK_SIDE)
    if p then
      id = p.id
    else
      local vals = tui.form("Sync to Disk", {
        { key = "id", label = "Passport ID", type = "text", required = true },
      })
      if not vals then return end
      id = vals.id
    end
  end
  local resp = net.request(serverId, { type = "get", id = id }, 6)
  if resp and resp.ok then
    local okw, errw = passport.writeDisk(config.DISK_SIDE, resp.data.record)
    if okw then
      tui.msgBox("Sync Complete", { ("Server data for %s written to disk"):format(id) })
      monitorShow(resp.data.record)
    else
      tui.msgBox("Sync Failed", { errw or "Disk write failed" })
    end
  else
    local e = (resp and resp.data and resp.data.error) or "Server not responding"
    tui.msgBox("Sync Failed", { tostring(e) })
  end
end

local function actSyncUp()
  if not periph.disk then
    tui.msgBox("Upload", { "No disk drive (" .. config.DISK_SIDE .. ")" })
    return
  end
  local p, err = passport.readDisk(config.DISK_SIDE)
  if not p then
    tui.msgBox("Upload Failed", { err or "Read failed" })
    return
  end
  if not serverId then refreshServer() end
  if not serverId then
    tui.msgBox("Upload Failed", { "No server found" })
    return
  end
  local resp = net.request(serverId, { type = "register", data = p }, 6)
  if resp and resp.ok then
    local saved = resp.data.record
    if saved and saved.id ~= p.id then
      p = saved
      passport.writeDisk(config.DISK_SIDE, p) -- 服务器分配的编号回写软盘
    end
    tui.msgBox("Upload Complete", {
      ("Uploaded %s (%s)"):format(p.id, resp.data.isNew and "new" or "update"),
    })
  else
    local e = (resp and resp.data and resp.data.error) or "Server not responding"
    tui.msgBox("Upload Failed", { tostring(e) })
  end
end

local function actStatus()
  if not serverId then refreshServer() end
  if not serverId then
    tui.msgBox("Server Status", {
      "No passport server found",
      "Check: server computer is running and has a modem",
    })
    return
  end
  local resp = net.request(serverId, { type = "stats" }, 5)
  if resp and resp.ok then
    local s = resp.data.stats
    tui.msgBox("Server Status", {
      ("Server computer: #%d"):format(serverId),
      ("Version: %s"):format(config.VERSION),
      ("Total passports: %d"):format(s.total),
      ("Valid %d  Revoked %d  Expired %d"):format(s.active, s.revoked, s.expired),
      ("Next ID: %s"):format(s.nextID),
    })
  else
    -- 服务器可能重启换了 ID, 重新发现一次
    refreshServer()
    if serverId then
      tui.msgBox("Server Status", { ("Re-discovered server #%d"):format(serverId) })
    else
      tui.msgBox("Server Status", { "Server not responding (offline?)" })
    end
  end
end

local function actSettings()
  local values = tui.form("Set Server ID (0=auto-detect)", {
    { key = "server", label = "Server ID", type = "number", default = tostring(config.SERVER_ID) },
  })
  if not values then return end
  config.SERVER_ID = tonumber(values.server) or 0
  config.save()
  refreshServer()
  tui.msgBox("Settings Saved", {
    ("Server ID: %d"):format(config.SERVER_ID),
    config.SERVER_ID == 0 and "Auto-detect server when needed" or "Use manually specified server",
  })
end

------------------------------------------------------------------------------
-- 主循环
------------------------------------------------------------------------------

scanPeriphs()
local modemOk, modemErr = net.open()
if modemOk then
  refreshServer()
end

-- 启动提示(调制解调器缺失时)
if not modemOk then
  tui.msgBox("Modem", {
    modemErr or "No modem found",
    "Network unavailable; disk-local features only",
  })
end

local lastServerCheck = 0
while true do
  scanPeriphs()
  -- 离线时每 15 秒尝试重新发现服务器(rednet.lookup 会阻塞约 2 秒)
  if not serverId and os.time() - lastServerCheck >= 15 then
    lastServerCheck = os.time()
    refreshServer()
  end

  tui.frame("Passport System v" .. config.VERSION, statusText())
  local sel = tui.menu("Select action", {
    { label = "Issue Passport" },
    { label = "View Passport" },
    { label = "Edit Passport" },
    { label = "Stamp Visa" },
    { label = "Sync: Server to Disk" },
    { label = "Upload: Disk to Server" },
    { label = "Server Status" },
    { label = "Settings" },
    { label = "Exit" },
  })
  if not sel then break end -- Esc 退出
  if sel == 1 then actIssue()
  elseif sel == 2 then actView()
  elseif sel == 3 then actEdit()
  elseif sel == 4 then actStamp()
  elseif sel == 5 then actSyncDown()
  elseif sel == 6 then actSyncUp()
  elseif sel == 7 then actStatus()
  elseif sel == 8 then actSettings()
  elseif sel == 9 then break end
end

term.setBackgroundColor(colors.black)
term.setTextColor(colors.white)
term.clear()
term.setCursorPos(1, 1)
print("Exited Passport System.")
]==],
}
local layouts = {
  server = {
    "lib/config.lua",
    "lib/passport.lua",
    "lib/db.lua",
    "server.lua",
  },
  client = {
    "lib/config.lua",
    "lib/passport.lua",
    "lib/net.lua",
    "lib/tui.lua",
    "client.lua",
  },
}

local target = arg and arg[1] or "client"
if not layouts[target] then
  print("Usage: install <server|client>")
  return
end

term.clear()
term.setCursorPos(1, 1)
print("Passport System - installer")
print("Target: " .. target)
print("--------------------------------")
local count = 0
for _, path in ipairs(layouts[target]) do
  local dir = fs.getDir(path)
  if dir and dir ~= "" and not fs.isDir("/" .. dir) then
    fs.makeDir("/" .. dir)
  end
  local f = fs.open("/" .. path, "w")
  if not f then
    printError("Failed to write: " .. path)
    printError("Check disk space or permissions")
    return
  end
  f.write(files[path])
  f.close()
  count = count + 1
  print("Installed /" .. path)
end
print("--------------------------------")
print(("Done! Installed %d files."):format(count))
if target == "server" then
  print("Start: type server")
else
  print("Start: type client")
end
print("Rename the entry file to startup.lua for auto-start")