# Passport System packaging script.
# Embeds all Lua sources into a single install.lua for in-game one-click deploy.
# NOTE: keep this script ASCII-only (PowerShell 5.1 reads .ps1 as ANSI/GBK).
# Usage: powershell -ExecutionPolicy Bypass -File tools\package.ps1
# Output: install.lua (repo root)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot

# Files to embed, in install order.
$files = @(
    "lib/config.lua",
    "lib/passport.lua",
    "lib/net.lua",
    "lib/tui.lua",
    "lib/db.lua",
    "server.lua",
    "client.lua"
)

# Guard: source must not contain long-bracket delimiters that would break install.lua.
foreach ($rel in $files) {
    $path = Join-Path $root ($rel -replace "/", "\")
    $content = [System.IO.File]::ReadAllText($path) -replace "`r`n", "`n"
    if ($content.Contains("]==]")) {
        Write-Error ("File {0} contains ']==]', would break install.lua delimiters!" -f $rel)
    }
    if ($content.Contains("[==[")) {
        Write-Error ("File {0} contains '[==[', would break install.lua delimiters!" -f $rel)
    }
}

$sb = New-Object System.Text.StringBuilder

# NOTE: use Append(.. + "`n") instead of AppendLine to keep LF-only output.
[void]$sb.Append("--[[`n")
[void]$sb.Append("  Passport System - one-click installer (auto-generated by tools/package.ps1, do not edit)`n")
[void]$sb.Append("  Usage: install server    # run on the server computer`n")
[void]$sb.Append("         install client    # run on each client computer`n")
[void]$sb.Append("]]`n")
[void]$sb.Append("local files = {`n")

foreach ($rel in $files) {
    $path = Join-Path $root ($rel -replace "/", "\")
    $content = [System.IO.File]::ReadAllText($path) -replace "`r`n", "`n"
    $content = $content -replace "`n$", ""   # strip trailing newline
    [void]$sb.Append('  ["' + $rel + '"] = [==[')
    [void]$sb.Append($content)
    [void]$sb.Append("`n]==],`n")
}

[void]$sb.Append("}`n")

[void]$sb.Append(@'
local layouts = {
  server = {
    "lib/config.lua",
    "lib/passport.lua",
    "lib/db.lua",
    "server.lua",
  },
  client = {
    "lib/config.lua",
    "lib/passport.lua",
    "lib/net.lua",
    "lib/tui.lua",
    "client.lua",
  },
}

local target = arg and arg[1] or "client"
if not layouts[target] then
  print("Usage: install <server|client>")
  return
end

term.clear()
term.setCursorPos(1, 1)
print("Passport System - installer")
print("Target: " .. target)
print("--------------------------------")
local count = 0
for _, path in ipairs(layouts[target]) do
  local dir = fs.getDir(path)
  if dir and dir ~= "" and not fs.isDir("/" .. dir) then
    fs.makeDir("/" .. dir)
  end
  local f = fs.open("/" .. path, "w")
  if not f then
    printError("Failed to write: " .. path)
    printError("Check disk space or permissions")
    return
  end
  f.write(files[path])
  f.close()
  count = count + 1
  print("Installed /" .. path)
end
print("--------------------------------")
print(("Done! Installed %d files."):format(count))
if target == "server" then
  print("Start: type server")
else
  print("Start: type client")
end
print("Rename the entry file to startup.lua for auto-start")
'@)

$out = Join-Path $root "install.lua"
[System.IO.File]::WriteAllText($out, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host ("Generated install.lua (" + (Get-Item $out).Length + " bytes)")
